export const LOGIN = 'LOGIN'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const ADD_USER = 'ADD_USER'
export const USERS_LIST = 'USERS_LIST'
export const USER_ONLINE = 'USER_ONLINE'
export const CLEAR_STATE = 'CLEAR_STATE'
export const USER_OFFLINE = 'USER_OFFLINE'
export const VIEW_USERS = 'VIEW_USERS'
